import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generarReportePDF = (datos) => {
  const { idAuditoria, porcentaje, detalles, hallazgos, etapas } = datos;
  const doc = new jsPDF();
  
  // Colores del diseño de Stitch
  const primaryGreen = [47, 238, 124]; // #2fee7c
  const charcoal = [26, 26, 26]; // #1a1a1a
  const grayLight = [156, 163, 175]; // text-gray-400

  // --- ENCABEZADO (Logo + Nombre) ---
  doc.setFillColor(...charcoal);
  doc.roundedRect(14, 15, 8, 8, 2, 2, 'F'); // El cuadrito del logo
  doc.setFontSize(14);
  doc.setTextColor(...charcoal);
  doc.setFont("helvetica", "bold");
  doc.text("Quality Control Hub", 25, 21);

  // --- TÍTULO PRINCIPAL ---
  doc.setFontSize(10);
  doc.setTextColor(...primaryGreen);
  doc.text("• Audit Completed", 14, 35);
  
  doc.setFontSize(28);
  doc.setTextColor(...charcoal);
  doc.setFont("helvetica", "bold");
  doc.text("REPORT ANALYSIS 5S", 14, 48);

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.setFont("helvetica", "normal");
  doc.text(`Audit ID: #${idAuditoria.toString().padStart(4, '0')}`, 14, 58);
  doc.text(`Last updated: ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`, 150, 58);

  // --- TARJETAS DE RESUMEN ---
  // Tarjeta Score
  doc.setDrawColor(240);
  doc.roundedRect(14, 65, 85, 40, 4, 4, 'S');
  doc.setFontSize(9);
  doc.setTextColor(...grayLight);
  doc.text("TOTAL SCORE", 20, 75);
  doc.setFontSize(35);
  doc.setTextColor(...primaryGreen);
  doc.text(`${porcentaje}%`, 20, 92);
  
  // Tarjeta Observations
  doc.roundedRect(110, 65, 85, 40, 4, 4, 'S');
  doc.setFontSize(9);
  doc.setTextColor(...grayLight);
  doc.text("KEY OBSERVATIONS", 116, 75);
  doc.setFontSize(24);
  doc.setTextColor(...charcoal);
  doc.text(`${hallazgos.length}`, 116, 88);
  doc.setFontSize(9);
  doc.text("Points Checked", 128, 88);

  // --- TABLA DE ETAPAS (Estilo idéntico a la imagen) ---
  const tableData = etapas.map(etapa => {
    const info = detalles[etapa.id] || {};
    const score = Math.round(info.score ?? 0);
    return [
      { content: `${etapa.n}\n${etapa.sub || ''}`, styles: { fontStyle: 'bold' } },
      info.comment || "No specific observations recorded for this stage.",
      `${score}/5`,
      score >= 4 ? "Pass" : "Fail"
    ];
  });

  autoTable(doc, {
    startY: 115,
    head: [['STAGE', 'DETAILED OBSERVATION', 'SCORE', 'STATUS']],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: primaryGreen, 
      textColor: charcoal, 
      fontSize: 9,
      fontStyle: 'bold'
    },
    styles: { 
      fontSize: 9,
      cellPadding: 6,
      lineColor: [240, 240, 240],
      textColor: [74, 74, 74]
    },
    columnStyles: {
      0: { cellWidth: 40 },
      2: { halign: 'center', fontStyle: 'bold' },
      3: { halign: 'center' }
    },
    didParseCell: function(data) {
      if (data.column.index === 3 && data.cell.section === 'body') {
        const isPass = data.cell.raw === 'Pass';
        data.cell.styles.textColor = isPass ? [34, 197, 94] : [239, 68, 68];
        data.cell.styles.fontStyle = 'bold';
      }
    }
  });

  // --- FOOTER ---
  const finalY = doc.internal.pageSize.height - 20;
  doc.setFontSize(8);
  doc.setTextColor(...grayLight);
  doc.text(`Emission Date: ${new Date().toLocaleDateString()}`, 14, finalY);
  doc.text(`Generated by Quality Control Hub System v2.4`, 14, finalY + 5);
  doc.text(`Page 1 of 1`, 180, finalY);

  doc.save(`Reporte_5S_${idAuditoria}.pdf`);
};